### ISSUE TITLE
DB Modell erstellen

### ISSUE THREAD

**Issue by soulday** [kuttnerdd/exam-manager#11]

**Comment by soulday** [comment]
[db_model_exam_manager.pdf](https://github.com/kuttnerdd/exam-manager/files/1437152/db_model_exam_manager.pdf)

Steht jetzt leider auf "closed" ... egal: Bitte mal anschauen, danke!

**Comment by B03hmi1986** [comment]
Ich eröffne das mal wieder...

**Comment by kuttnerdd** [comment]
Sieht gut aus, einzig die Urkunden (Abschlusszeugnis) vermisse ich noch. Diese ergibt sich aus den Credits+Pflichtmodulen+WPF. Die Anforderung mit Erstausfertigung, Zweit+ Drittschrift muss mE von uns in der DB nicht modelliert werden ... reicht so auch schon ;-)
Oder bin ich hier falsch gewickelt? 
Die Notenliste+Sortierung (mit/ohne 5.0/NE) lässt sich ja gut über das FE abwickeln.

**Comment by Lucil1979** [comment]
Wenn ich es richtig sehen fehlt die Anzahl an Wiederholungen bei der Prüfung max ist ja 3 würde dafür ein Byte Feld anlegen.

**Comment by soulday** [comment]
So, habe die meisten Anregungen/Korrekturen aufgenommen - bis auf Deine, Daniel. Meines Erachtens ist das Zeugnis keine eigene Tabelle, sondern ein Dokument, dessen Inhalt über SQL-Abfragen gefüllt wird. Oder ist das Quatsch?

[db_model_exam_manager.pdf](https://github.com/kuttnerdd/exam-manager/files/1454514/db_model_exam_manager.pdf)

**Comment by soulday** [comment]
Hallo zusammen,
nachdem ich mich bilateral mit Dirk über die DB ausgetauscht und die übrigen Hinweise auch eingearbeitet habe, stelle ich hier das Ergebnis vor.
[db_model_exam_manager_v3.pdf](https://github.com/kuttnerdd/exam-manager/files/1485461/db_model_exam_manager_v3.pdf)

Das Modell kann ich als DB-Struktur gleich in eine mySQL importieren, habe da derzeit nur noch ein Problem mit den FK. Zur Not muss ich den Feinschliff manuell machen. Die views (gelb) sind erstmal noch nicht mit den richtigen SQL-statements verknüpft. 

Ich hoffe, ich habe alles berücksichtigt, aber das ist relativ komplex geworden. Insofern bin ich für Anmerkungen und weitere Hinweise dankbar.
Viele Grüße
Paul
