### ISSUE TITLE
Attribute Verbesserungvorschlag

### ISSUE THREAD

**Issue by B03hmi1986** [kuttnerdd/exam-manager#14]
Student.hausNr --> VARCHAR(15) --> Was ist mit Hausnummer 5b oder 6d-f?
Student.plz --> VARCHAR(5) --> Bei 014.. bekommt man Probleme
Student.telMobil und Student.telFest --> VARCHAR() --> 04952 / 059684 od. +49491 / 8383843

Studiengang.Mindestzahl CP VARCHAR(45): Bei Student.Creditpoints INT und Bei Modul.Creditpoints auch INT. Bin mir nicht sicher aber ich glaube das lässt sich später schwer vergleichen und man möchte bestimmt Berechnungen zwischen den Creditpoints einbauen. (Strudiengang.Creditpoints -  Student.Creditpoints = noch offene Creditpoints)

**Comment by soulday** [comment]
Danke - ehrlich gesagt hatte ich die Datentypen noch gar nicht im Detail durchdacht, macht aber alles Sinn!
