### ISSUE TITLE
Einigung der Programmiersprache

### ISSUE THREAD

**Issue by B03hmi1986** [kuttnerdd/exam-manager#15]
Welche Programmiersprache soll eingesetzt werden?

**Comment by soulday** [comment]
Mein Vorschlag:
Frontend in HTML5, ggf. JS oder TS
Datenbank mit mySQL
Backend-Logik (wenn überhaupt erforderlich...) in php; vllt kann man das aber sogar allein mit SQL erledigen. Was wir aber in jedem Fall brauchen ist eine print-Funktion für die Zeugnisse usw. Und dafür ist eine eigene Backend-Logik vermutlich unumgänglich.

**Comment by Lucil1979** [comment]
Ok also PHP schauen wir doch mal was wir da für eine Printlogik hinbekommen
